# Dependencies
markdown: redcarpet

pygments: false

# Permalinks
permalink: pretty

# Setup
title: planning poker web
url: planning-poker.github.io/planning-poker-game

author:
  name: planning-poker.github.io

exclude:
  - "Gruntfile.coffee"
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - ".gitignore"
  - "README.md"

include:
  - .nojekyll
